name: Terraform Azure Pipeline

on:
  push:
    branches:
      - features/pipeline

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Azure Login using Service Principal
      - name: Azure Login with Service Principal
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "3b912ffd-594c-4b81-a37b-dae19e9bc0c9",
              "clientSecret": "3LW8Q~D6JxomR.pO2pt4nQy8wzZ18DFGcdoQHc4_",
              "tenantId": "fde3126b-b5b9-4d9e-ab0c-f949118194f2",
              "subscriptionId": "4b65089c-f974-4b72-8aa1-3a5821bc947a"
            }

      # 4. Check Azure Login
      - name: Check Azure Login
        run: az account show

      # 5. Terraform Init
      - name: Terraform Init
        run: terraform init

      # 6. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 7. Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        
       # 8. Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve